
CREATE TABLE IF NOT EXISTS user (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS booking (
   id INT AUTO_INCREMENT PRIMARY KEY,
   user_id INT,
   date DATE NOT NULL,
   half_day BOOLEAN NOT NULL,
   status VARCHAR(50) NOT NULL,
FOREIGN KEY (user_id) REFERENCES user(id)
);
